language: php


matrix:
  include:
    - php: 5.5.9
    - php: 5.5
    - php: 5.6
    - php: 7.0
    - php: 7.1
    - php: hhvm
      dist: trusty

sudo: false

before_install: cp .env.example .env

install: travis_retry composer install --no-interaction --no-scripts --prefer-source

script: vendor/bin/phpunit
