language: php

sudo: false

dist: trusty

php:
  - 5.5.9
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - hhvm

before_install:
  - cp .env.example .env
  - if [[ $TRAVIS_PHP_VERSION == hhvm ]]; then echo 'hhvm.jit = false' >> /etc/hhvm/php.ini; fi

install: travis_retry composer install --no-interaction --no-suggest

notifications:
  email: false

script: vendor/bin/phpunit
